version: "3"

services:
  scraper:
    build: 
        context: ./Scraper
    tty: true
    environment:
        DB_HOST: db
        DB_PORT: 5432
        DB_NAME: postgres
        DB_USER: postgres
        DB_PASSWORD: somePassword
    depends_on:
      - "db"
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: somePassword
  node:
    build: 
        context: ./Node
    ports:
      - "8080:8080"
  react:
    build: 
        context: ./React
    ports:
      - "80:80"

